version: '2'
volumes: 
    db-data:
    telegram-data:
services:
  telegram-frontend:
    privileged: true
    restart: always
    depends_on:
      - db
    build: ./telegram-frontend
    volumes: 
            - 'telegram-data:/root/telegram'
  db:
    image: i386/postgres
    restart: always
    ports:
    - "5432:5432"
    volumes: 
            - 'db-data:/var/lib/postgresql/data'