version: '2'
volumes: 
    db-data:
services:
  telegram-frontend:
    privileged: true
    restart: always
    build: ./telegram-frontend
  db:
    image: i386/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretpassword
    ports:
    - "5432:5432"